services:
  tc-ui-eng:
    image: rdeangel/tc-ui-eng:v1.0.11
    container_name: tc-ui-eng
    network_mode: host
    tty: true
    stdin_open: true
    privileged: true
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      #- FB_DATABASE=/etc/filebrowser/database.db
    volumes: 
      - '/lib/modules:/lib/modules:ro'
    restart: unless-stopped
