name: "Release tc-ui-eng"

on:
  push:
    tags:
      - v1*

jobs:
  envs:
    name: envs
    steps:
      ##################################################################################################################
      # Git checkout
      - name: Checkout repository
        uses: actions/checkout@v3
      # The github.ref is, for example, refs/tags/v5.0.145 or refs/tags/v5.0-r8
      # Generate variables like:
      #   TC_UI_TAG=v1.0.52
      #   TC_UI_MAJOR=1
      # @see https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Generate varaiables
        run: |
          TC_UI_TAG=$(echo ${{ github.ref }}| awk -F '/' '{print $3}')
          echo "TC_UI_TAG=$TC_UI_TAG" >> $GITHUB_ENV
          TC_UI_MAJOR=$(echo $TC_UI_TAG| awk -F '.' '{print $1}' |sed 's/v//g')
          echo "TC_UI_MAJOR=$TC_UI_MAJOR" >> $GITHUB_ENV
    # Map a step output to a job output, see https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
    outputs:
      TC_UI_TAG: ${{ env.TC_UI_TAG }}
      TC_UI_MAJOR: ${{ env.TC_UI_MAJOR }}
    runs-on: ubuntu-20.04

  docker:
    needs:
      - envs
    steps:
      - name: Covert output to env
        run: |
          echo "TC_UI_TAG=${{ needs.envs.outputs.TC_UI_TAG }}" >> $GITHUB_ENV
          echo "TC_UI_MAJOR=${{ needs.envs.outputs.TC_UI_MAJOR }}" >> $GITHUB_ENV
      # Git checkout
      - name: Checkout repository
        uses: actions/checkout@v3
      # See https://github.com/crazy-max/ghaction-docker-buildx#moved-to-docker-organization
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Create main images for Docker
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - name: Build the ui for multiple archs
        run: |
          echo "Build multiple arch ui"
          cd ui && npm install && npm run build
      - name: Build TC-UI-ENG docker image
        run: |
          echo "Release rdeangel/tc-ui-eng:$TC_UI_TAG"
          docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64/v8 \
            --output "type=image,push=true" --build-arg MAKEARGS=build-no-ui \
            --tag rdeangel/tc-ui-eng:$TC_UI_TAG -f Dockerfile .
      - name: Docker alias images for rdeangel/tc-ui
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: rdeangel/tc-ui-eng:${{ env.TC_UI_TAG }}
          dst: |
            rdeangel/tc-ui-eng:${{ env.TC_UI_MAJOR }}
            rdeangel/tc-ui-eng:v${{ env.TC_UI_MAJOR }}
            rdeangel/tc-ui-eng:latest
    runs-on: ubuntu-20.04
